CREATE TABLE rprp_store_items (
    itemHash VARCHAR(36) PRIMARY KEY,
    itemDesc VARCHAR(255) NOT NULL,
    priceR DECIMAL(10, 2) NOT NULL,
    priceC DECIMAL(10, 2) NOT NULL,
    imgUrl VARCHAR(1000) NOT NULL,
    info TEXT,
    category VARCHAR(20) NOT NULL,
    perma BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);